In [1]:
import numpy

In [3]:
numpy.__version__

'1.25.1'

In [5]:
import numpy as np
np.__version__

'1.25.1'

In [6]:
arr0 = np.array(5)

In [7]:
print(arr0)

5


In [8]:
type(arr0)

numpy.ndarray

In [9]:
arr1 = np.array([5, 5, 3.4])

In [10]:
type(arr1)

numpy.ndarray

In [11]:
a1 = np.array([3, 6, 4, 1])
print(a1)
print(type(a1))
print(a1.ndim)

[3 6 4 1]
<class 'numpy.ndarray'>
1


In [2]:
import numpy as np


a = np.array(7)
print(a)
print(type(a))
print(a.ndim)

7
<class 'numpy.ndarray'>
0


In [3]:
my_list = []
c = np.array(my_list)
print(type(c))

<class 'numpy.ndarray'>


In [4]:
for i in range(1,5):
    x = int(input('element : '))
    my_list.append(x)
    
d = np.array(my_list)
print(d)

element : 7
element : 6
element : 9
element : 3
[7 6 9 3]


In [7]:
j = np.linspace(0,10, num= 3)
j

array([ 0.,  5., 10.])

In [8]:
k = np.random.rand(4)
k

array([0.58369264, 0.69644623, 0.44982295, 0.16388887])

In [9]:
l = np.random.randn(6)
l

array([ 0.50648016, -0.22120783, -0.54801875,  0.9901872 , -0.26090937,
       -1.56774966])

In [11]:
m = np.random.ranf(6)
m

array([0.9438135 , 0.01156251, 0.55087835, 0.36000161, 0.15626367,
       0.35834927])

In [12]:
n = np.random.randint(4, 20, 5)
n

array([14,  8, 10, 10,  4])

In [13]:
p = np.array(['Mukesh','Nirmal', 'Bhagwan'])
p

array(['Mukesh', 'Nirmal', 'Bhagwan'], dtype='<U7')

In [14]:
q = np.array([2,5,8,7], dtype = np.int8)
print(q)
print(q.dtype)


[2 5 8 7]
int8


In [15]:
b = [i**2 for i in range(1,15)]
b

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [17]:
%timeit np.arange(1,20)**3

1.74 µs ± 18.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [23]:
f = np.array([8,3,5], ndmin = 30)
f

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[8, 3, 5]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [27]:
h = np.zeros((10,9))
h

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
k = np.eye(4,6)
k

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [29]:
l = np.random.rand(3,4)
l

array([[0.93152489, 0.4216817 , 0.01254437, 0.86288794],
       [0.24856812, 0.61523144, 0.39675827, 0.40223698],
       [0.73198194, 0.90048075, 0.81259407, 0.12650005]])

# 27-09-2023

In [2]:
import numpy
a = numpy.array([[6,4,3,5],[2,4,3,5]])
a.shape

(2, 4)

In [4]:
g = numpy.array([
    [7,3,8,],
    [6,8,3]
])
g[1,2]

3

In [5]:
h = numpy.array([[[8,3,5],[7,2,4]]])
h.shape

(1, 2, 3)

In [7]:
h[0]

array([[8, 3, 5],
       [7, 2, 4]])

In [8]:
h[0,1,2]

4

In [9]:
a = numpy.array([4,2,6,4])
b = numpy.array([8,3,4,6])
a+b

array([12,  5, 10, 10])

In [12]:
numpy.add(a,b)

array([12,  5, 10, 10])

In [13]:
a-b

array([-4, -1,  2, -2])

In [14]:
a*b

array([32,  6, 24, 24])

In [15]:
a/b

array([0.5       , 0.66666667, 1.5       , 0.66666667])

In [16]:
b = numpy.array([54,32,45,67])
b.ndim

1

In [18]:
d = b.reshape(2,2)
d

array([[54, 32],
       [45, 67]])

In [22]:
e = numpy.array([4,6,8,6,8,4,])
f = e.reshape(1,3,2)
f

array([[[4, 6],
        [8, 6],
        [8, 4]]])

In [23]:
a = numpy.array([4,2,5,1])
b = numpy.array([5])
a+b

array([ 9,  7, 10,  6])

# 29/09/2023